### ISSUE TITLE
Permission denied since last update

### ISSUE THREAD

**Issue by petrsimunek** [Natizyskunk/vscode-sftp#35] opened 2021-08-23 12:45 UTC
After last update I am receiving Permission denied when uploading to server.

Target server Win2019 with OpenSSH
Files are PHP files.
I checked persmissions and rights on the server and these are OK.
I tried to manipulate the files over winSCP with the same account, and I have full rights on the server.

After upload a new file in target folder is created with ".new" extension, but not renamed to .php. (For example "index.php uploads as index.php.new and remains on the server like that.)

Downgrade to v1.14.0 works.

**Comment by FM-O** [comment] 2021-08-23 14:43
Hi @petrsimunek !
I ran into several issues with the new update too. If your problem is with the "new" extension added to uploaded files/folders, it's about the feature deployed with the last release.
See changelog here : https://github.com/Natizyskunk/vscode-sftp/releases/tag/v1.15.0
You can either downgrade your version to 1.14.0 (which I recommend since the last release seems not stable) or deactivate the "useTempFile" feature by setting the option to false in your sftp.json file (should work, but not tested).

If you tested to set the useTempFile to false let me know if it resolves your issue :)

**Comment by petrsimunek** [comment] 2021-08-23 15:31
Hi @FM-O ,

yes. Downgrading solves the issue. I just tried to upgrade back to 1.15.0 again and set the useTempFile false settings, and this works too. Thanks :-)

But I think, that this should be fixed anyway. :-)

**Comment by Natizyskunk** [comment] 2021-08-24 03:19
please use older 1.14.0 version since i'm working on a fix.

@kripper, can you please take a look at it ? Seems to be the same problem as the issue [#34](https://github.com/Natizyskunk/vscode-sftp/issues/34#issuecomment-904290206).

**Comment by kripper** [comment] 2021-08-24 07:55
Definitely related. It seems like there is a problem when trying to rename the .new file to target name.
Any hint to reproduce on my system?
Can you please add the extension logs?
What are the permissions of the remote files and folder?

@Natizyskunk please let's disable by default the new "useTempFile" option while we fix this issue.

**Comment by petrsimunek** [comment] 2021-08-24 08:22
Hi, I just noticed that extension was upgraded to 1.15.1. The difference is, that with the first attempt it shows "permission denied" and with the second attempt "no such file". The v1.15.0 gave the "permission denied" alert only.

Anyway "useTempFile" works.

I use VScode on windows with SFTP v1.15.1 now, target server is Win2019 with OpenSSH. User used in JSON config has the FULL RIGHTS on the folder.

Log here (there are both alerts in the log. "permission denied" and "no such file" after second save attempt:

[08-24 10:16:32] [info] [file-save] c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml
[08-24 10:16:32] [trace] handle upload file for c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml
[08-24 10:16:32] [debug] Outbound: Sending CHANNEL_DATA (r:0, 79)
[08-24 10:16:32] [debug] SFTP: Outbound: Buffered MKDIR
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:33] [debug] SFTP: Inbound: Received STATUS (id:16, 4, "Failure")
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 75)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered LSTAT
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-24 10:16:33] [debug] SFTP: Inbound: Received ATTRS (id:17)
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 95)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered OPEN
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 99)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered OPEN
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 10:16:33] [debug] SFTP: Inbound: Received HANDLE (id:18)
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 10:16:33] [debug] SFTP: Inbound: Received HANDLE (id:19)
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered FSTAT
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-24 10:16:33] [debug] SFTP: Inbound: Received ATTRS (id:20)
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered CLOSE
[08-24 10:16:33] [info] uploading temp file: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml.new
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 25)
[08-24 10:16:33] [debug] SFTP: Outbound: Buffered FSETSTAT
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:33] [debug] SFTP: Inbound: Received STATUS (id:21, 0, "Success")
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:33] [debug] SFTP: Inbound: Received STATUS (id:22, 0, "Success")
[08-24 10:16:33] [debug] Outbound: Sending CHANNEL_DATA (r:0, 1973)
[08-24 10:16:33] [debug] SFTP: Outbound: Sent WRITE (id:23)
[08-24 10:16:33] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:33] [debug] SFTP: Inbound: Received STATUS (id:23, 0, "Success")
[08-24 10:16:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[08-24 10:16:34] [debug] SFTP: Outbound: Buffered FSETSTAT
[08-24 10:16:34] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:34] [debug] SFTP: Inbound: Received STATUS (id:24, 0, "Success")
[08-24 10:16:34] [info] moving from: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml.new to: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml
[08-24 10:16:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 87)
[08-24 10:16:34] [debug] SFTP: Outbound: Buffered REMOVE
[08-24 10:16:34] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:34] [debug] SFTP: Inbound: Received STATUS (id:25, 0, "Success")
[08-24 10:16:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 169)
[08-24 10:16:34] [debug] SFTP: Outbound: Buffered RENAME
[08-24 10:16:34] [debug] Inbound: CHANNEL_DATA (r:0, 38)
[08-24 10:16:34] [debug] SFTP: Inbound: Received STATUS (id:26, 3, "Permission denied")
[08-24 10:16:34] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 10:16:34] [debug] SFTP: Outbound: Buffered CLOSE
[08-24 10:16:34] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:16:34] [debug] SFTP: Inbound: Received STATUS (id:27, 0, "Success")
[08-24 10:16:34] [error] Error: Permission denied
	at 101 (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\SFTP.js:2471:19)
	at SFTP.push (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\SFTP.js:271:11)
	at CHANNEL_DATA (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\client.js:505:23)
	at 94 (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\handlers.misc.js:841:16)
	at Protocol.onPayload (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:1974:10)
	at AESGCMDecipherNative.decrypt (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\crypto.js:992:26)
	at Protocol.parsePacket [as _parse] (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:1943:25)
	at Protocol.parse (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:281:16)
	at Socket.<anonymous> (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\client.js:692:21)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml
[08-24 10:16:57] [debug] Outbound: Sending ping (GLOBAL_REQUEST: keepalive@openssh.com)
[08-24 10:16:57] [debug] Inbound: Received REQUEST_FAILURE
[08-24 10:17:03] [info] [file-save] c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml
[08-24 10:17:03] [trace] handle upload file for c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml
[08-24 10:17:03] [debug] Outbound: Sending CHANNEL_DATA (r:0, 79)
[08-24 10:17:03] [debug] SFTP: Outbound: Buffered MKDIR
[08-24 10:17:03] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:17:03] [debug] SFTP: Inbound: Received STATUS (id:28, 4, "Failure")
[08-24 10:17:03] [debug] Outbound: Sending CHANNEL_DATA (r:0, 75)
[08-24 10:17:03] [debug] SFTP: Outbound: Buffered LSTAT
[08-24 10:17:03] [debug] Inbound: CHANNEL_DATA (r:0, 41)
[08-24 10:17:03] [debug] SFTP: Inbound: Received ATTRS (id:29)
[08-24 10:17:03] [debug] Outbound: Sending CHANNEL_DATA (r:0, 95)
[08-24 10:17:03] [debug] SFTP: Outbound: Buffered OPEN
[08-24 10:17:03] [debug] Outbound: Sending CHANNEL_DATA (r:0, 99)
[08-24 10:17:03] [debug] SFTP: Outbound: Buffered OPEN
[08-24 10:17:03] [debug] Inbound: CHANNEL_DATA (r:0, 33)
[08-24 10:17:03] [debug] SFTP: Inbound: Received STATUS (id:30, 2, "No such file")
[08-24 10:17:03] [debug] Inbound: CHANNEL_DATA (r:0, 17)
[08-24 10:17:03] [debug] SFTP: Inbound: Received HANDLE (id:31)
[08-24 10:17:03] [info] uploading temp file: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml.new
[08-24 10:17:03] [debug] Outbound: Sending CHANNEL_DATA (r:0, 1973)
[08-24 10:17:03] [debug] SFTP: Outbound: Sent WRITE (id:32)
[08-24 10:17:04] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:17:04] [debug] SFTP: Inbound: Received STATUS (id:32, 0, "Success")
[08-24 10:17:04] [debug] Outbound: Sending CHANNEL_DATA (r:0, 29)
[08-24 10:17:04] [debug] SFTP: Outbound: Buffered FSETSTAT
[08-24 10:17:04] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:17:04] [debug] SFTP: Inbound: Received STATUS (id:33, 0, "Success")
[08-24 10:17:04] [info] moving from: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml.new to: /DATA/invoices-dev/www-root/app/WebModule/History/Views/Upload/index.phtml
[08-24 10:17:04] [debug] Outbound: Sending CHANNEL_DATA (r:0, 87)
[08-24 10:17:04] [debug] SFTP: Outbound: Buffered REMOVE
[08-24 10:17:04] [debug] Inbound: CHANNEL_DATA (r:0, 33)
[08-24 10:17:04] [debug] SFTP: Inbound: Received STATUS (id:34, 2, "No such file")
[08-24 10:17:04] [debug] Outbound: Sending CHANNEL_DATA (r:0, 17)
[08-24 10:17:04] [debug] SFTP: Outbound: Buffered CLOSE
[08-24 10:17:04] [debug] Inbound: CHANNEL_DATA (r:0, 28)
[08-24 10:17:04] [debug] SFTP: Inbound: Received STATUS (id:35, 0, "Success")
[08-24 10:17:04] [error] Error: No such file
	at 101 (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\SFTP.js:2471:19)
	at SFTP.push (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\SFTP.js:271:11)
	at CHANNEL_DATA (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\client.js:505:23)
	at 94 (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\handlers.misc.js:841:16)
	at Protocol.onPayload (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:1974:10)
	at AESGCMDecipherNative.decrypt (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\crypto.js:992:26)
	at Protocol.parsePacket [as _parse] (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:1943:25)
	at Protocol.parse (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\protocol\Protocol.js:281:16)
	at Socket.<anonymous> (c:\Users\petrs.WIN-LO06JUOJ7OD\.vscode\extensions\natizyskunk.sftp-1.15.1\node_modules\ssh2\lib\client.js:692:21)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) when local ➞ remote c:\_DATA\OneDrive\PROJEKTY\2021\2021-WEB-VG-Invoices\development\VG-invoices\app\WebModule\History\Views\Upload\index.phtml

**Comment by kripper** [comment] 2021-08-24 12:23
Please test again once PR https://github.com/Natizyskunk/vscode-sftp/pull/41 is merged and released.
It seems like the "rename" command (from temp file to target file) failed because either file has wrong permissions.

**Comment by Natizyskunk** [comment] 2021-08-24 14:57
Could you try new release and tell me if the bug has been fixed please ?

**Comment by petrsimunek** [comment] 2021-08-24 18:57
Hi @Natizyskunk , it works now! :-) Thanks!

**Comment by Natizyskunk** [comment] 2021-08-24 19:14
no problem, i'm glad to hear that ! 😁

**Closed by Natizyskunk** 2021-08-24 19:14 UTC
